/state/partition1/llgrid/pkg/anaconda2-5.0.1/lib/python2.7/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
INFO:tensorflow:Summary name dense1/dense1_2/activation sparsity is illegal; using dense1/dense1_2/activation_sparsity instead.
INFO:tensorflow:Summary name dense2/dense2_2/activation sparsity is illegal; using dense2/dense2_2/activation_sparsity instead.
INFO:tensorflow:Summary name logits/logits_2/activation sparsity is illegal; using logits/logits_2/activation_sparsity instead.
INFO:tensorflow:Summary name training accuracy is illegal; using training_accuracy instead.
INFO:tensorflow:Summary name dense1/weight_loss (raw) is illegal; using dense1/weight_loss__raw_ instead.
INFO:tensorflow:Summary name dense2/weight_loss (raw) is illegal; using dense2/weight_loss__raw_ instead.
INFO:tensorflow:Summary name logits/weight_loss (raw) is illegal; using logits/weight_loss__raw_ instead.
INFO:tensorflow:Summary name cross_entropy (raw) is illegal; using cross_entropy__raw_ instead.
INFO:tensorflow:Summary name total_loss (raw) is illegal; using total_loss__raw_ instead.
INFO:tensorflow:Updating masks.
INFO:tensorflow:Summary name dense1/mask:0/sparsity is illegal; using dense1/mask_0/sparsity instead.
INFO:tensorflow:Summary name dense2/mask:0/sparsity is illegal; using dense2/mask_0/sparsity instead.
INFO:tensorflow:Summary name logits/mask:0/sparsity is illegal; using logits/mask_0/sparsity instead.
INFO:tensorflow:Create CheckpointSaverHook.
2018-08-21 01:33:31.122382: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2018-08-21 01:33:31.586888: E tensorflow/core/common_runtime/bfc_allocator.cc:244] tried to allocate 0 bytes
2018-08-21 01:33:31.586979: W tensorflow/core/common_runtime/allocator_retry.cc:32] Request to allocate 0 bytes
2018-08-21 01:33:31.587021: E tensorflow/core/common_runtime/bfc_allocator.cc:378] tried to deallocate nullptr
2018-08-21 01:33:31.601439: E tensorflow/core/common_runtime/bfc_allocator.cc:244] tried to allocate 0 bytes
2018-08-21 01:33:31.601498: W tensorflow/core/common_runtime/allocator_retry.cc:32] Request to allocate 0 bytes
2018-08-21 01:33:31.601532: E tensorflow/core/common_runtime/bfc_allocator.cc:378] tried to deallocate nullptr
ERROR:tensorflow:Couldn't match files for checkpoint /home/gridsan/salford/Kepner-sparse-nn/saved/prune/lenet31_p3/model.ckpt-201
Warning: model directory already exists. If meant to retrain previous model, this is normal
Extracting ../../data/mnist/train-images-idx3-ubyte.gz
Extracting ../../data/mnist/train-labels-idx1-ubyte.gz
Extracting ../../data/mnist/t10k-images-idx3-ubyte.gz
Extracting ../../data/mnist/t10k-labels-idx1-ubyte.gz
No checkpoint found; training from scratch
Traceback (most recent call last):
  File "train.py", line 299, in <module>
    train_mnist()
  File "train.py", line 169, in train_mnist
    + RESTORE_DIR)
ValueError: Restore dir cant find checkpoint fles: /home/gridsan/salford/Kepner-sparse-nn/saved/prune/lenet31_p3_prune_ckpts/0.1/
